---
title: "Playground"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
theme_set(theme_light())
```

```{r}
set.seed(42)
N <- 2000
x <- arm::rescale(rnorm(N))
b_0 <- c(-4, -3)
b_1 <- c(-4, 3)
b_prop <- c(0.2, 1.3)

prob_0 <- plogis(cbind(rep(1, N), x) %*% b_0)
plot(x, prob_0, ylim = c(0, 1))

prob_1 <- plogis(cbind(rep(1, N), x) %*% b_1)
plot(x, prob_1, ylim = c(0, 1))

prop_mu <- plogis(cbind(rep(1, N), x) %*% b_prop)
plot(x, prop_mu, ylim = c(0, 1))

phi <- 20
p <- prop_mu * phi
q <- phi - prop_mu * phi

y_0 <- c(FALSE, TRUE)[rbinom(N, size = 1, prob = prob_0) + 1]
plot(x, y_0)
y_1 <- c(FALSE, TRUE)[rbinom(N, size = 1, prob = prob_1 * (1 - prob_0)) + 1]
plot(x, y_1)
y_prop <- rbeta(N, shape1 = p, shape2 = q)
plot(x, y_prop)

y <- y_prop
y[y_0 == TRUE] <- 0
y[y_1 == TRUE] <- 1

plot(x, prop_mu, ylim = c(0, 1))
points(x, prob_1 + (1 - prob_1) * prop_mu, ylim = c(0, 1), col = "red")
legend("topleft", col = c("red", "black"), pch = c(21, 21), legend = c("Pr(1) and proportion combined", "proportion only"))

plot(x, y, ylim = c(0, 1))
y_true <- (1 - prob_0) * (prob_1 + (1 - prob_1) * prop_mu)
o <- order(x)
lines(x[o], y_true[o])

dat <- data.frame(x = x, y = y)
```


```{r}
yp <- y[!y_0 & !y_1]
xp <- x[!y_0 & !y_1]
plot(xp, yp)

y0 <- ifelse(y == 0, 1, 0)
x0 <- x
plot(x0, y0, ylim = c(0, 1))

y1 <- ifelse(y == 1, 1, 0)
x1 <- x
plot(x1, y1, ylim = c(0, 1))

N0 <- length(y0)
N1 <- length(y1)
Np <- length(yp)

library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

stan_dat <- list(
  N0 = N0, 
  N1 = N1, 
  Np = Np,
  J01 = 2L,
  Jp = 2L,
  X0_ij = cbind(rep(1, N0), x0),
  X1_ij = cbind(rep(1, N1), x1),
  Xp_ij = cbind(rep(1, Np), xp),
  y0_i = y0,
  y1_i = y1,
  yp_i = yp
)
sm <- stan_model("zoib1.stan")
# m <- optimizing(sm, data = stan_dat)

m <- sampling(sm,
  data = stan_dat,
  iter = 300L, chains = 4L,
  pars = c("b0_j", "b1_j", "bp_j", "phi")
)
m
```

```{r}
Npred <- 200L
x_pred <- seq(min(x), max(x), length.out = Npred)
e <- rstan::extract(m)

pred_p <- plogis(cbind(rep(1, Npred), x_pred) %*% t(e$bp_j))
plot(x_pred, apply(pred_p, 1, median), ylim = c(0, 1))
points(xp, yp, col = "#00000030")
lines(x[o], prop_mu[o], col = "blue", lwd = 2)

pred_0 <- plogis(cbind(rep(1, Npred), x_pred) %*% t(e$b0_j))
plot(x_pred, apply(pred_0, 1, median), ylim = c(0, 1))
points(x, y0, col = "#00000030")
lines(x[o], prob_0[o], col = "blue", lwd = 2)

pred_1 <- plogis(cbind(rep(1, Npred), x_pred) %*% t(e$b1_j))
plot(x_pred, apply(pred_1, 1, median), ylim = c(0, 1))
points(x, y1, col = "#00000030")
lines(x[o], prob_1[o], col = "blue", lwd = 2)

y_pred <- (1 - pred_0) * (pred_1 + (1 - pred_1) * pred_p)

pred_df <- data.frame(
  x = x_pred,
  est = apply(y_pred, 1, quantile, probs = 0.5),
  lwr = apply(y_pred, 1, quantile, probs = 0.05),
  upr = apply(y_pred, 1, quantile, probs = 0.95)
)

ggplot(pred_df, aes(x, est, ymin = lwr, ymax = upr)) +
  geom_point(data = dat, aes(x, y), inherit.aes = FALSE, alpha = 0.5) +
  geom_ribbon(alpha = 0.5) +
  geom_line(colour = "red", lwd = 1) +
  ylim(0, 1) +
  geom_line(data = data.frame(x = x[o], true = y_true[o]), aes(x = x, y = true), 
    col = "blue",
    inherit.aes = FALSE)
```

Real data:

```{r}
d <- read_csv("ALL_SHOBS_2010_2014_PLOTS_MASTER_w_CO_FINAL_20171029.csv")
d <- select(d, BOLESCORCH, RdNBR, FIRE) %>%
  na.omit() %>% as.data.frame() %>% as_tibble() %>% 
  rename(y = BOLESCORCH, x = RdNBR, group = FIRE) %>%
  filter(x < 2500) %>% 
  mutate(y0 = ifelse(y == 0, 1, 0),
    y1 = ifelse(y == 1, 1, 0),
    yp = ifelse(y == 0 | y == 1, NA, y),
    xscaled = arm::rescale(x),
    group = as.factor(tolower(group)),
    group_id = as.integer(group)) %>% 
  arrange(group_id, x)

dp <- filter(d, !is.na(yp))

N0 <- nrow(d)
N1 <- nrow(d)
Np <- nrow(dp)

f0 <- y0 ~ xscaled + group - 1
f1 <- y1 ~ xscaled + group - 1
fp <- y ~ xscaled + group - 1
mm0 <- as.matrix(model.matrix(f0, data = d))
mm1 <- as.matrix(model.matrix(f1, data = d))
mmp <- as.matrix(model.matrix(fp, data = dp))

stan_dat <- list(
  N0 = N0, 
  N1 = N1, 
  Np = Np,
  J01 = ncol(mm0),
  Jp = ncol(mmp),
  X0_ij = mm0,
  X1_ij = mm1,
  Xp_ij = mmp,
  y0_i = d$y0,
  y1_i = d$y1,
  yp_i = dp$y
)
# sm <- stan_model("zoib1.stan")
# m <- optimizing(sm, data = stan_dat)

m <- sampling(sm,
  data = stan_dat,
  iter = 1000L, chains = 4L,
  pars = c("b0_j", "b1_j", "bp_j", "phi")
)
m
```

```{r}
Npred <- 200L
d_pred <- expand.grid(
  xscaled = seq(min(d$xscaled), max(d$xscaled), length.out = Npred),
  group = unique(d$group), y = 1)
e <- rstan::extract(m)

mm_pred <- as.matrix(model.matrix(fp, data = d_pred))

pred_p <- plogis(mm_pred %*% t(e$bp_j))
plot(d_pred$xscaled, apply(pred_p, 1, median), ylim = c(0, 1), type = "p")
points(dp$xscaled, dp$y)

pred_0 <- plogis(mm_pred %*% t(e$b0_j))
plot(d_pred$xscaled, apply(pred_0, 1, median), ylim = c(0, 1), type = "p")

pred_1 <- plogis(mm_pred %*% t(e$b1_j))
plot(d_pred$xscaled, apply(pred_1, 1, median), ylim = c(0, 1), type = "p")

y_pred <- (1 - pred_0) * (pred_1 + (1 - pred_1) * pred_p)

pred_df <- data.frame(
  xscaled = d_pred$xscaled,
  group = d_pred$group,
  est = apply(y_pred, 1, quantile, probs = 0.5),
  lwr = apply(y_pred, 1, quantile, probs = 0.1),
  upr = apply(y_pred, 1, quantile, probs = 0.9)
)

ggplot(pred_df, aes(xscaled, est, ymin = lwr, ymax = upr, group = group)) +
  geom_point(data = d, aes(xscaled, y, colour = group), 
    inherit.aes = FALSE, alpha = 0.6) +
  geom_ribbon(alpha = 0.1, fill = "grey50") +
  geom_line(aes(colour = group), lwd = 1) +
  ylim(0, 1)
```

RE

```{r}
f0 <- y0 ~ xscaled
f1 <- y1 ~ xscaled
fp <- y ~ xscaled
mm0 <- as.matrix(model.matrix(f0, data = d))
mm1 <- as.matrix(model.matrix(f1, data = d))
mmp <- as.matrix(model.matrix(fp, data = dp))

stan_dat <- list(
  N0 = N0, 
  N1 = N1, 
  Np = Np,
  J01 = ncol(mm0),
  Jp = ncol(mmp),
  X0_ij = mm0,
  X1_ij = mm1,
  Xp_ij = mmp,
  y0_i = d$y0,
  y1_i = d$y1,
  yp_i = dp$y,
  
  Ng = length(unique(d$group)),
  group_id0 = d$group_id,
  group_id1 = d$group_id,
  group_idp = dp$group_id
)

m <- stan("zoib1re.stan",
  data = stan_dat,
  iter = 1000L, chains = 4L,
  pars = c("b0_j", "b1_j", "bp_j", "phi", "sigma_z", "z0_g", "z1_g", "zp_g"),
  control = list(adapt_delta = 0.95)
)
m
```

```{r}
Npred <- 200L
d_pred <- expand.grid(
  xscaled = seq(min(d$xscaled), max(d$xscaled), length.out = Npred),
  group_id = unique(d$group_id), y = 1)
e <- rstan::extract(m)

mm_pred <- as.matrix(model.matrix(fp, data = d_pred))

pred_p <- plogis(mm_pred %*% t(e$bp_j))
plot(d_pred$xscaled, apply(pred_p, 1, median), ylim = c(0, 1))
pred_0 <- plogis(mm_pred %*% t(e$b0_j))
plot(d_pred$xscaled, apply(pred_0, 1, median), ylim = c(0, 1))
pred_1 <- plogis(mm_pred %*% t(e$b1_j))
plot(d_pred$xscaled, apply(pred_1, 1, median), ylim = c(0, 1))

pred_p_re <- mm_pred %*% t(e$bp_j)
pred_p_re <- apply(pred_p_re, 1, median)
zp_g <- apply(e$zp_g, 2, median)

pred_0_re <- mm_pred %*% t(e$b0_j)
pred_0_re <- apply(pred_0_re, 1, median)
z0_g <- apply(e$z0_g, 2, median)

pred_1_re <- mm_pred %*% t(e$b1_j)
pred_1_re <- apply(pred_1_re, 1, median)
z1_g <- apply(e$z1_g, 2, median)

d_pred$pred_p_re <- plogis(pred_p_re + rep(zp_g, each = Npred))
d_pred$pred_0_re <- plogis(pred_0_re + rep(z0_g, each = Npred))
d_pred$pred_1_re <- plogis(pred_1_re + rep(z1_g, each = Npred))

y_pred <- (1 - pred_0) * (pred_1 + (1 - pred_1) * pred_p)
d_pred$y_pred_re <- (1 - d_pred$pred_0_re) * (d_pred$pred_1_re + (1 - d_pred$pred_1_re) * d_pred$pred_p_re)

pred_df <- data.frame(
  xscaled = d_pred$xscaled,
  group = d_pred$group_id,
  est = apply(y_pred, 1, quantile, probs = 0.5),
  lwr = apply(y_pred, 1, quantile, probs = 0.025),
  upr = apply(y_pred, 1, quantile, probs = 0.975),
  est_re = d_pred$y_pred_re,
  x = d_pred$xscaled * 2 * sd(d$x) + mean(d$x)
)

ggplot(pred_df, aes(x, est, ymin = lwr, ymax = upr)) +
  geom_point(data = d, aes(x, y, colour = group), 
    inherit.aes = FALSE, alpha = 0.6) +
  geom_line(aes(y = est_re, group = as.factor(group)), 
    col = "grey50", lty = 1, lwd = 0.2) +
  geom_line(lwd = 1.5) +
  geom_ribbon(alpha = 0.5, fill = "grey20") +
  ylim(0, 1)
```

AUC

```{r}
mm <- as.matrix(model.matrix(fp, data = d))

pred_p <- plogis(mm %*% t(e$bp_j))
pred_0 <- plogis(mm %*% t(e$b0_j))
pred_1 <- plogis(mm %*% t(e$b1_j))

y_pred <- (1 - pred_0) * (pred_1 + (1 - pred_1) * pred_p)

# https://gist.github.com/traversc/1446ebe1dcc2d84bccdca781d4f1fa2a
fastROC <- function(probs, class) {
  class_sorted <- class[order(probs, decreasing=T)]
  TPR <- cumsum(class_sorted) / sum(class)
  FPR <- cumsum(class_sorted == 0) / sum(class == 0)
  return(data.frame(tpr=TPR, fpr=FPR))
}
fastAUC <- function(probs, class) {
  x <- probs
  y <- class
  x1 = x[y==1]; n1 = length(x1); 
  x2 = x[y==0]; n2 = length(x2);
  r = rank(c(x1,x2))  
  auc = (sum(r[1:n1]) - n1*(n1+1)/2) / n1 / n2
  return(auc)
}

probs <- apply(y_pred, 1, median)
thresh <- seq(0.05, 0.95, length.out = 20)

auc_thresh <- function(thresh = 0.5) {
  d$outcome <- ifelse(d$y > thresh, 1, 0)
  fastAUC(class = d$outcome, probs = probs)
}
a <- sapply(thresh, auc_thresh)
# hist(a)

roc_thresh <- function(thresh = 0.5) {
  d$outcome <- ifelse(d$y > thresh, 1, 0)
  fastROC(class = d$outcome, probs = probs)
}

lab <- paste0("AUC range = ", round(min(a), 2), " - ", round(max(a), 2))
lab1 <- paste0("mean AUC = ", round(mean(a), 2))
r <- plyr::ldply(thresh, roc_thresh)
r$thresh <- rep(thresh, each = length(probs))
ggplot(r, aes(fpr, tpr)) +
  geom_line(aes(group = as.factor(thresh), colour = thresh), alpha = 0.9) +
  scale_color_gradient2(mid = "grey75", midpoint = 0.5) +
  geom_text(data = data.frame(fpr = 0.75, tpr = 0.1), label = lab) +
  geom_text(data = data.frame(fpr = 0.75, tpr = 0.15), label = lab1)
```

